# Generated by Django 4.2.5 on 2023-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_alter_calendarentry_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='user_image',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
