# Generated by Django 4.2.5 on 2023-10-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_calendarentry_calendar_alter_calendarentry_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarentry',
            name='username',
        ),
    ]
